services:
  - type: web
    name: moodify-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: ./start.sh
    runtime: python
    region: oregon
    branch: main
    repo: https://github.com/<your-username>/<your-repo>
